# Define project parent directories to create aliases
PROJECT_PARENT_DIRS=()

# Load sources
source $HOME/.zsh/config/colors.zsh
source $HOME/.zsh/config/general.zsh
source $HOME/.zsh/config/modules.zsh
source $HOME/.zsh/config/bindings.zsh
