# Define project parent directories to create aliases
PROJECT_PARENT_DIRS=()

# Load personal settings
if [[ -f $HOME/.zsh/config/personal.zsh ]]; then
  source $HOME/.zsh/config/personal.zsh
fi

# Load sources
source $HOME/.zsh/config/colors.zsh
source $HOME/.zsh/config/general.zsh
source $HOME/.zsh/config/modules.zsh
source $HOME/.zsh/config/bindings.zsh
source $HOME/.zsh/config/rvm.zsh
source $HOME/.zsh/config/options.zsh
source $HOME/.zsh/config/completion.zsh
source $HOME/.zsh/config/title.zsh
source $HOME/.zsh/config/git.zsh
source $HOME/.zsh/config/rbenv.zsh
source $HOME/.zsh/config/ruby.zsh
